version: '3'
services: 

  db:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: "111111"
      MYSQL_DATABASE: kpt

  adminer:
    image: adminer
    ports:
      - 9999:8080

  web:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./cmd:/go/src/github.com/mivinci/kpt/cmd
    restart: always
